### ISSUE TITLE
Inscription : loader

### ISSUE THREAD

**Issue by ld-web** [Alexg3888/Projet_YMA_Client#5]
Lors du clic sur "Envoyer", ajouter un loader pour indiquer à l'utilisateur que la requête est en cours de traitement.
Vous pourrez aussi désactiver le bouton "Envoyer" lors du chargement, pour éviter que l'utilisateur ne clique X fois dessus et envoie donc X requêtes d'inscription au serveur.

**Comment by yannred** [comment]
réglé
